name: Build

on:
  workflow_dispatch:
    pull_request:
      branches:
        - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
      - run: npm ci
      - run: npm run build
        env:
          API_PATH: "placeholder"
          FIREBASE_CLIENT_EMAIL: "placeholder"
          FIREBASE_PRIVATE_KEY: "placeholder"
          FIREBASE_PROJECT_ID: "placeholder"
