name: Publish
on:
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Get latest code"
        uses: actions/checkout@v3

      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1

      - name: "Install node dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build
        env:
          FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
          FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
          FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}

      - name: "Delete node_modules directory"
        run: rm -rf node_modules

      - name: "Push to server"
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: './*'
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
