name: Publish
on:
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Get latest code"
        uses: actions/checkout@v3

      - name: "Sync files"
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: './*'
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
